### PR TITLE
reply links, popup reply on mousehover over link

### PR DESCRIPTION
**Pull request by overloop**
lets make meow even better for all cryptoanarchists in the world

### CODE REVIEW

**Comment by Kagami** [comment]
:kissing_heart:

**Comment by Kagami** [comment]
Looks good, thanks. Will deploy it asap.
Small tip for future contributions: try to manipulate DOM using jQuery DOM methods like `.attr()`, `.addClass()` and so on. While in this particular case it shouldn't matter, in general it may save from danger XSS vulnerability.

**Comment by overloop** [comment]
Cool! Thanks for advice.

**Comment by Kagami** [comment]
Deployed.
Small design nitpick: I think it would be better to display replies under the comment not above it (like on 2ch.hk for example, I think it's rather usable and intuitive).
You may help and contribute it or I may do it by myself in some "near" future.

**Comment by border-radius** [comment]
:+1:

**Comment by Kagami** [comment]
Or maybe in the top-right corner of the message (like on 8chan). There are a lot of empty place which could be used for replies.

**Comment by border-radius** [comment]
+1 for top-right corner

**Comment by border-radius** [comment]
Also deployed to the [6nw](http://6nw.im).

**Comment by overloop** [comment]
I don't mind it be anywhere, actually. I put it in left upper corner because that way it requires less mouse movemets to watch chain of answers and bottom of browser (and right border) window are not getting reached that fast, on the other hand with links at the bottom we see all comments in chain (do we realy need to see them when we read them one second ago, though). Of corse it also depends on where we show popup (where mouse pointer relative to popup - top left corner seems most intuiteve to me). (I feel helples when i reach bottom of screen and can go any further).
lefttopcorner

**Comment by Kagami** [comment]
Replies may popup in the opposite direction if they reached the border of the screen (like it done in 2ch.hk/dollchan scripts for example). Though it would require more code to handle that.

**Comment by 4DA** [comment]
Please add delay (.5 ms) after which pop-up is displayed. Instantaneous pop-ups are unzbl in case your mouse pointer merely crosses the reply without the intention to view the pop-up.

**Comment by border-radius** [comment]
Bug report: when you rebnwiting some post, it lost all replies links.

**Comment by overloop** [comment]
4DA, I don't think delay is a good idea. UI must be fast and responsive, not slow and annoying, or it will feels like it lags or network lags or javascript lags, or your computer lags. And why would you wait for things that you can have immediately?

**Comment by border-radius** [comment]
@overloop it's just because @4da is slow and reactive interface make him feel uncomfortable. There should be a neural network which should adapt interface response time with user responsiveness to make illusion of slowness equality. Nobody wants to feed themselves slower than Javascript.

**Comment by overloop** [comment]
hm? hmmm? ;) ;) hm?

**Comment by 4DA** [comment]
I've made my case; i don't always want to see popups, but with as for now i
can't cross the reply link with mouse cursor without triggering the popup.

On Sun, Jan 25, 2015 at 2:35 PM, Doronin Stanislav <notifications@github.com
> wrote:

> 4DA, I don't think delay is a good idea. UI must be fast and responsive,
> not slow and annoying, or it will feels like it lags or network lags or
> javascript lags, or your computer lags. And why would you wait for things
> that you can have immediately?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kagami/bnw-meow/pull/91#issuecomment-71368002>.
>



-- 
With best regards,
Dmitry

**Pull request merged**
